[package]
name = "akari_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akari_render = {path = "../akari_render"}

[lib]
crate-type = ["cdylib"]