[package]
edition = "2021"
name = "akari_render"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akari_common.workspace = true
akari_data.workspace = true
akari_scenegraph.workspace = true
akari_cpp_ext.workspace = true

[build-dependencies]
cmake.workspace = true
serde.workspace = true
serde_json.workspace = true

# [lib]
# crate-type = ["dylib"]
