[package]
name = "pyakari"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyakari"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
akari_core = {path = "../akari_core"}
akari_scenegraph = { path = "../akari_scenegraph" }
mimalloc = "0.1.43"