[package]
name = "akari_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

rayon = "1.8"
base64 = "0.22"
memmap2 = "0.9"
sha2 = "0.10"
libm = "0.2"
winit = "0.29"
glam = "0.27" # need syn with luisa_compute
exr = "1.5"
hexf = "0.2"
image = "0.25"
indicatif = "0.17"
lazy_static = "1"
log = "0.4"
luisa_compute = { path = "../../../luisa-compute-rs/luisa_compute", features = [
    "glam",
    # "oidn",
] }
parking_lot = "0.12"
rand = "0.9"
bevy_mikktspace = "0.15"
libc = "0.2"
ddsfile = "0.5.2"