[package]
name = "akari_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akari_render.workspace = true
akari_integrator.workspace = true
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]


[[bin]]
name = "akari-cli"
path = "src/bin/akari_cli.rs"

[[bin]]
name = "akari-test"
path = "src/bin/akari_test.rs"
