[package]
name = "akari_scenegraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akari_common.workspace = true
akari_cpp_ext.workspace = true

[build-dependencies]
bindgen.workspace = true
cmake.workspace = true

# [lib]
# crate-type = ["dylib"]

[[bin]]
name = "akari-import"
path = "src/bin/import.rs"
