if(AKR_ENABLE_EMBREE)
    set(AKR_COMPILE_DEFINITIONS ${AKR_COMPILE_DEFINITIONS} AKR_ENABLE_EMBREE)
    if(NOT AKR_USE_PREBUILT_EMBREE)
        set(EMBREE_ISPC_SUPPORT           OFF CACHE BOOL " " FORCE)
        set(EMBREE_TUTORIALS              OFF CACHE BOOL " " FORCE)
        set(EMBREE_FILTER_FUNCTION        ON CACHE BOOL " " FORCE)
        set(EMBREE_GEOMETRY_QUAD          OFF CACHE BOOL " " FORCE)
        set(EMBREE_GEOMETRY_CURVE         OFF CACHE BOOL " " FORCE)
        set(EMBREE_GEOMETRY_GRID          OFF CACHE BOOL " " FORCE)
        set(EMBREE_GEOMETRY_SUBDIVISION   OFF CACHE BOOL " " FORCE)
        set(EMBREE_GEOMETRY_INSTANCE      ON CACHE BOOL " " FORCE)
        set(EMBREE_GEOMETRY_USER          OFF CACHE BOOL " " FORCE)
        set(EMBREE_STATIC_LIB             ON  CACHE BOOL " " FORCE)
        set(EMBREE_MAX_ISA AVX2 CACHE STRING  "" FORCE)
        # set(EMBREE_ISA_SSE2 ON CACHE BOOL "" FORCE)
        # set(EMBREE_ISA_SSE42 ON CACHE BOOL "" FORCE)
        # set(EMBREE_ISA_AVX ON CACHE BOOL "" FORCE)
        # set(EMBREE_ISA_AVX2 ON CACHE BOOL "" FORCE)
        set(EMBREE_GEOMETRY_POINT OFF CACHE BOOL "" FORCE)
        set(EMBREE_TASKING_SYSTEM INTERNAL CACHE STRING "" FORCE)
        # set(EMBREE_IGNORE_CMAKE_CXX_FLAGS OFF CACHE BOOL "" FORCE)
        set(EMBREE_INCLUDE_DIRS external/embree/include)
        add_subdirectory(external/embree)
        set(EMBREE_LIBRARY embree embree_sse42 embree_avx embree_avx2)
    else()
        IF(WIN32)
            set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "C:/Program Files/Intel/Embree3 x64")
        ELSE()
            set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "/usr/lib64/cmake/")
        ENDIF()
        find_package(embree 3.12 REQUIRED)
        IF(NOT embree_FOUND)
            message("Embree 3.12 not found; Falling back to custom BVH backend")
        ELSE()
            message("Embree found " ${EMBREE_INCLUDE_DIRS})
        ENDIF()
    endif()

endif()