IF(WIN32)
    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "C:/Program Files (x86)/LLVM/lib/cmake")
ELSE()
#    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "/usr/lib64/cmake/")
ENDIF()

find_package(LLVM 8.0)
if(NOT LLVM_FOUND)
    message(FATAL_ERROR "LLVM not found")
else()
    message(STATUS "Found LLVM ${LLVM_VERSION}")
    message(STATUS "LLVM_INCLUDE_DIR " ${LLVM_INCLUDE_DIR})
    message(STATUS "LLVM_LIBRARY_DIRS    " ${LLVM_LIBRARY_DIRS})
endif()