find_package(LLVM REQUIRED CONFIG)
if(NOT LLVM_FOUND)
    message(FATAL_ERROR "LLVM not found")
else()
    message(STATUS "Found LLVM ${LLVM_VERSION}")
    message(STATUS "LLVM_INCLUDE_DIR" ${LLVM_INCLUDE_DIR})
endif()