include(ExternalProject)

if(AKR_ENABLE_OIDN)
    if(AKR_USE_PREBUILT_OIDN)
        find_package(OpenImageDenoise)
    else()
        add_subdirectory(external/oidn)
        set(OIDN_INCLUDE_DIRS external/oidn/include)
    endif()
endif()